In [2]:
import numpy as np
a1 = np.array([1,2,3])

In [3]:
a2 = np.array([4,5,6])

In [4]:
a1 + a2

array([5, 7, 9])

In [5]:
a = np.array([[1,2],[3,4],[5,6]])

In [6]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a.ndim

2

In [8]:
a.dtype

dtype('int32')

In [9]:
a.shape

(3, 2)

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,5)

array([0, 5])

In [14]:
#linearly spaced number between 1 to 5 and 10 leanrly spaced
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [19]:
# ravel makes is flattened
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [20]:
a.min()

1

In [22]:
a.max()

6

In [23]:
# sum all the numbers
a.sum()

21

In [24]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
# axis = 0 for all the columns
a.sum(axis = 0)

array([ 9, 12])

In [27]:
# axis = 1 for all the rows
a.sum(axis= 1)

array([ 3,  7, 11])

In [29]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [30]:
np.std(a)

1.707825127659933

In [31]:
a.mean()

3.5

In [34]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [35]:
b = np.array([[5,6],[7,8]])

In [38]:
b

array([[5, 6],
       [7, 8]])

In [36]:
a+b

array([[ 6,  8],
       [10, 12]])

In [37]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [39]:
a

array([[1, 2],
       [3, 4]])

In [40]:
b

array([[5, 6],
       [7, 8]])

In [41]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])

In [42]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [43]:
a[1,2]

3

In [44]:
a[0:2]

array([[6, 7, 8],
       [1, 2, 3]])

In [45]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [46]:
a[0:2,2]

array([8, 3])

In [48]:
a[-1,0:2]

array([9, 3])

In [49]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [54]:
# how to flatten an array
for cell in a.flat:
    print(cell)
        

6
7
8
1
2
3
9
3
2


In [55]:
a.ravel()

array([6, 7, 8, 1, 2, 3, 9, 3, 2])

In [56]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [57]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [58]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [59]:
# how to stack them togather
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [60]:
# horizontal stack
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [62]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [64]:
# how to slice them in the middle and make 3 equal array
result = np.hsplit(a,3)

In [65]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [66]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [67]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [68]:
# split them vertically
result = np.vsplit(a,2)

In [70]:
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [74]:
a = np.arange(12).reshape(3,4)

In [75]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
# find out numbers greater than 4
b = a[a>4]
b


array([ 5,  6,  7,  8,  9, 10, 11])

In [77]:
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
# using for loop to iterate them
for row in a:
    for col in row:
        print(col)

0
1
2
3
4
5
6
7
8
9
10
11


In [80]:
# there is another way to flatten it
for row in a.flatten():
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [81]:
# same flatten we can use nditer using order = c order
for x in np.nditer(a,order= 'C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [84]:
# fortran order
for x in np.nditer(a,order = 'F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11
